version: '3'
services:
  go-app:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
    volumes:
      - .:/app

  mail:
    image: bytemark/smtp
    restart: always
    
  rabbitmq:
    image: "rabbitmq:3.9.5-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "rok"
      RABBITMQ_DEFAULT_PASS: "rokjecar"
